### ISSUE TITLE
Use in browser environment

### ISSUE THREAD

**Issue by corwin-of-amber** [mafintosh/simple-hypercore-protocol#5]
I used to be able to use `hypercore-protocol` (7.5.1) in client-side code running in a browser. Newer `hypercore-protocol` (9.5.0) based on `simple-hypercore-protocol` depends on `noise-protocol` and `sodium-native`, which are Node.js only.

Is there a way to substitute `sodium-universal` for `sodium-native`, which would allow working in both environments? This may require a change in `noise-protocol` as well -- unless you are aware of a way to substitute a module like in https://github.com/defunctzombie/package-browser-field-spec that will also span into module dependencies.

**Comment by RangerMauve** [comment]
Check out the docs in dat-sdk for compiling for use in Browsers with either Webpack or Browserify: https://github.com/datproject/sdk#compile-with-webpack-webpackconfigjs

**Comment by corwin-of-amber** [comment]
Yeah cool, I figured this hack myself, was just wondering if there couldn't be a simpler way around it.
(that is, something that involves the configuration of `simple-hypercore-protocol` and not the user's.)

**Comment by corwin-of-amber** [comment]
Actually, that link says that Browserify should work out of the box and aliasing is only needed for Webpack. Is that right? Seems a bit weird because how is Browserify going to know?

**Comment by RangerMauve** [comment]
The browserify instructions there are for dat-sdk. Check out the browserify config stuff to see how it works

**Comment by corwin-of-amber** [comment]
Hmm AFAICT the `browser` field in `package.json` only affects the current module. That's what https://github.com/moll/browserify-substitution-mass-confusion is for.

**Comment by DougAnderson444** [comment]
I'm trying to run this in the browser using the `dat-sdk` and I get this error

```
Uncaught TypeError: data.copy is not a function
    at ProtocolHandshake.onsend 
    at SimpleHandshake.send 
    at start 
    at Item../node_modules/process/browser.js.Item.run 
    at drainQueue 
```

This happens after I make my copy of a hyperdrive

```
const copy = Hyperdrive2(originalKey);
await copy.ready();
```
I think this simple-hypercore-protocol may be expects a `buffer` but the browser isn't giving it one. I'd love to trace the route back from drainQueue but I'm not that familiar with how the code flows... but from a bit of digging it looks like the

```
const payload = {
  nonce: XOR.nonce()
}
``` 
[is not](https://github.com/mafintosh/simple-hypercore-protocol/blob/89cfbdde2a0ffa8ff89272efdcd34caebd373fdf/index.js#L10) a buffer? Just a hypothesis, but is there a UIntArray/Buffer issue at `getRandomBytes` somewhere [near here](https://github.com/sodium-friends/sodium-javascript/blob/a546f3e51d4496b18f4d565339bd06c0ccbc0527/randombytes.js#L9) when the payload is the nonce in the browser?

**Comment by DougAnderson444** [comment]
I switch from webpack to browserify and got it to work without errors. I think my above issue was a webpack issue,
Of note, I needed to use the `const once = require("events.once")` polyfill to make the magic happen.

**Comment by corwin-of-amber** [comment]
@DougAnderson444 is this related to `hypercore-protocol`? Or are you using the stable release of `dat-sdk`, which uses `hyper-protocol` 7.x.x?

**Comment by DougAnderson444** [comment]
I'm using the latest `dat sdk`

**Comment by rjmackay** [comment]
I've been fighting the same issue getting `Uncaught TypeError: data.copy is not a function` when using webpack.
As far as I've traced it, it seems the Buffer.subarray doesn't return a Buffer. The bug was fixed here: https://github.com/feross/buffer/pull/263 but webpack still uses an old version via node-libs-browser

**Comment by rjmackay** [comment]
Ended up with this solution in my webpack config:
```
    node: {
      Buffer: false
    },
    plugins: [
      new webpack.ProvidePlugin({
        'Buffer': [path.join(__dirname, 'node_modules/buffer/index.js'), 'Buffer'],
      }),
    ],
```
The path.join is to make sure we pick up the latest buffer, not the old one. 
This might be easier in webpack v5 since it doesn't shim Buffer itself.

**Comment by dmaretskyi** [comment]
I'm running into `Buffer.concat` being called with an instance of `Uint8Array`. The error happens here https://github.com/mafintosh/simple-hypercore-protocol/blob/395711fb51803fd793d5439cc7804fe3844e68b3/lib/handshake.js#L113

Looks like the `Uint8Array` is coming from the `sodium_malloc`.

**Comment by RangerMauve** [comment]
Can this be closed now that #7 has landed?

**Comment by corwin-of-amber** [comment]
Thanks for checking in @RangerMauve, #7 looks like it would work -- I will have to test this.

**Comment by corwin-of-amber** [comment]
Still haven't tested it, but looking at #7 again, it works around the `Buffer.concat` problem but does not affect the original issue, namely the `noise-protocol` dependency.

However, seemingly this happened at some point: https://github.com/emilbayes/noise-protocol/commit/e38e8864abf4edc034e1d85f57bcb577a9b4a037, and soon after the OP above it was incorporated into https://github.com/mafintosh/simple-hypercore-protocol/commit/daf65692ec5318bbb48f19c9d20a32a86ba169af. So looks promising.

**Comment by RangerMauve** [comment]
Sweet. If you get a chance to test this out do let us know how it goes. 😁

I've gotten stuff working with some fairly gross monkey patching with browserify, but it'd be nice if I could remove all that for the happy path of whatever this is.

**Comment by corwin-of-amber** [comment]
Ooh yeah! With hypercore@9.11.0 (which uses simple-hypercore-protocol@2.1.1) I can build it without the mass-confusion plugin. Awesome!

**Comment by RangerMauve** [comment]
Heck yeah! Gonna close this for now.

Feel free to open a new issue if there's something else that comes up, or comment her so we can reopen it to debug if there are further problems. 😁
